---
title: "fMRI"
author: "Yanan Ren"
date: "2016Äê11ÔÂ9ÈÕ"
output: word_document
---

```{r, echo=FALSE}
setwd("D:/Biostatistics/2016FallRA/")
fMRI<-read.csv("dataset/ketamine_clusters_r.csv", header=T, sep=',')
attach(fMRI)
View(fMRI)

##mean and sd##
mean_fMRI<-as.data.frame(apply(fMRI[,2:ncol(fMRI)], 2, mean))
mean_fMRI
baseline_mean<-round(mean_fMRI[1:21,],3)
baseline_mean
ptx_trt_mean<-round(mean_fMRI[22:42,],3)
ptx_trt_mean

sd_fMRI<-as.data.frame(apply(fMRI[,2:ncol(fMRI)], 2, sd))
sd_fMRI
baseline_sd<-round(sd_fMRI[1:21,],3)
baseline_sd
ptx_trt_sd<-round(sd_fMRI[22:42,],3)
ptx_trt_sd

Baseline<-paste(baseline_mean,"¡À",baseline_sd, sep=" ")
Baseline
Post_treatment<-paste(ptx_trt_mean,"¡À",ptx_trt_sd, sep=" ")
Post_treatment

names<-colnames(fMRI)
newname<-substr(names[2:22],10,nchar(names[2:22]))

fMRI_table<-data.frame(newname,Baseline,Post_treatment)

library(knitr)
kable(fMRI_table, caption = "Table 1. Baseline and Post-treatment of fMRI")
```

##2
```{r, echo=FALSE}
cdrs_prechange<-c(0.41,-0.14,0.29,0.30,0.24,0.675,0.78,0.59)
L_hipp_L_insula_diff<-fMRI[,23]-fMRI[,2]
L_hipp_ACC_diff<-fMRI[,24]-fMRI[,3]
L_postcing_Lfusiform_diff<-fMRI[,25]-fMRI[,4]
L_postcing_precentral_postcentral_diff<-fMRI[,26]-fMRI[,5]
L_postcing_R_frontal_pole_diff<-fMRI[,27]-fMRI[,6]
R_rostralACC_subcallosal_diff<-fMRI[,28]-fMRI[,7]
R_rostralACC_frontal_pole_diff<-fMRI[,29]-fMRI[,8]
R_precuneus_postcentral_diff<-fMRI[,30]-fMRI[,9]
R_precuneus_R_fusiform_diff<-fMRI[,31]-fMRI[,10]
R_precuneus_R_hippocampus_diff<-fMRI[,32]-fMRI[,11]
R_precuneus_superior_frontal_diff<-fMRI[,33]-fMRI[,12]
R_precuneus_insula_diff<-fMRI[,34]-fMRI[,13]
R_hipp_L_insula_diff<-fMRI[,35]-fMRI[,14]
R_hipp_subcallosal_diff<-fMRI[,36]-fMRI[,15]
R_hipp_postcing_diff<-fMRI[,37]-fMRI[,16]
R_hipp_superior_frontal_diff<-fMRI[,38]-fMRI[,17]
R_amyg_thalamus_hippocampus_diff<-fMRI[,39]-fMRI[,18]
L_amyg_ACC_diff<-fMRI[,40]-fMRI[,19]
L_precuneus_L_postcing_diff<-fMRI[,41]-fMRI[,20]
L_precuneus_L_precentral_SMA_diff<-fMRI[,42]-fMRI[,21]
L_precuneus_R_precentral_diff<-fMRI[,43]-fMRI[,22]

table.cor<-data.frame(cdrs_prechange, L_hipp_L_insula_diff, L_hipp_ACC_diff, L_postcing_Lfusiform_diff, L_postcing_precentral_postcentral_diff, L_postcing_R_frontal_pole_diff, R_rostralACC_subcallosal_diff, R_rostralACC_frontal_pole_diff, R_precuneus_postcentral_diff, R_precuneus_R_fusiform_diff, R_precuneus_R_hippocampus_diff, R_precuneus_superior_frontal_diff, R_precuneus_insula_diff, R_hipp_L_insula_diff, R_hipp_subcallosal_diff, R_hipp_postcing_diff, R_hipp_superior_frontal_diff, R_amyg_thalamus_hippocampus_diff, L_amyg_ACC_diff, L_precuneus_L_postcing_diff, L_precuneus_L_precentral_SMA_diff, L_precuneus_R_precentral_diff)
View(table.cor)
##one sample t-test##
## one sample t-test for diff with Ho: mu=0 Ha=greater 
##0.3318621 p-value = 0.1671
t.test(table.cor[,2], mu=0, alternative="greater", conf.level=0.95)

##-0.2707354 p-value = 0.6929
t.test(table.cor[,3], mu=0, alternative="greater", conf.level=0.95)

##0.1294889 p-value = 0.386
t.test(table.cor[,4], mu=0, alternative="greater", conf.level=0.95)

## -0.639403 p-value = 0.8651
t.test(table.cor[,5], mu=0, alternative="greater", conf.level=0.95)

## -0.08661625 p-value = 0.5639
t.test(table.cor[,6], mu=0, alternative="greater", conf.level=0.95)

##-0.4005255   p-value = 0.787
t.test(table.cor[,7], mu=0, alternative="greater", conf.level=0.95)

## -0.6373602 p-value = 0.8277
t.test(table.cor[,8], mu=0, alternative="greater", conf.level=0.95)

##-0.544049  p-value = 0.805
t.test(table.cor[,9], mu=0, alternative="greater", conf.level=0.95)

##-0.031733  p-value = 0.5227
t.test(table.cor[,10], mu=0, alternative="greater", conf.level=0.95)

## -0.07100963 p-value = 0.552
t.test(table.cor[,11], mu=0, alternative="greater", conf.level=0.95)
## 0.2252616 p-value = 0.3529
t.test(table.cor[,12], mu=0, alternative="greater", conf.level=0.95)
## 0.3066747 p-value =0.2985 
t.test(table.cor[,13], mu=0, alternative="greater", conf.level=0.95)

## 0.328511 p-value = 0.1775
t.test(table.cor[,14], mu=0, alternative="greater", conf.level=0.95)

## -0.05843263 p-value = 0.5702
t.test(table.cor[,15], mu=0, alternative="greater", conf.level=0.95)

##  -0.03911 p-value = 0.5429
t.test(table.cor[,16], mu=0, alternative="greater", conf.level=0.95)

## -0.3224361 p-value = 0.7627
t.test(table.cor[,17], mu=0, alternative="greater", conf.level=0.95)
## -0.2601389  p-value = 0.7314
t.test(table.cor[,18], mu=0, alternative="greater", conf.level=0.95)

## 0.1089519   p-value = 0.3982
t.test(table.cor[,19], mu=0, alternative="greater", conf.level=0.95)

## 0.4449994  p-value = 0.2564
t.test(table.cor[,20], mu=0, alternative="greater", conf.level=0.95)

## 0.568566  p-value = 0.0182
t.test(table.cor[,21], mu=0, alternative="greater", conf.level=0.95)

## -0.2798365  p-value = 0.6727
t.test(table.cor[,22], mu=0, alternative="greater", conf.level=0.95)

diff<-c(0.332,-0.271,0.129,-0.639,-0.087,-0.401,-0.637,-0.544,-0.032,-0.071,0.225,0.307,0.329,-0.058,-0.039,-0.322,-0.260,0.109,0.445,0.569,-0.280)
p.value<-c(0.167,0.693,0.386,0.865,0.564,0.787,0.828,0.805,0.523,0.552,0.353,0.299,0.178,0.570,0.543,0.763,0.731,0.398,0.256,0.018,0.673)
fMRI_table.2<-data.frame(newname,Baseline,Post_treatment,diff,p.value)

library(knitr)
kable(fMRI_table.2, caption = "Table 1. Baseline and Post-treatment of fMRI")
```

```{r,echo=FALSE}
##plot##
#par(mfrow=c(2,2))
plot(table.cor[,2],table.cor[,1], ylab="CDRS percent change", xlab="L_hipp_L_insula_diff")
plot(table.cor[,3],table.cor[,1], ylab="CDRS percent change", xlab="L_hipp_ACC_diff")
plot(table.cor[,4],table.cor[,1], ylab="CDRS percent change", xlab="L_postcing_Lfusiform_diff")
plot(table.cor[,5],table.cor[,1], ylab="CDRS percent change", xlab="L_postcing_precentral_postcentral_diff")

#par(mfrow=c(2,2))
plot(table.cor[,6],table.cor[,1], ylab="CDRS percent change", xlab="L_postcing_R_frontal_pole_diff")
plot(table.cor[,7],table.cor[,1], ylab="CDRS percent change", xlab="R_rostralACC_subcallosal_diff")
plot(table.cor[,8],table.cor[,1], ylab="CDRS percent change", xlab="R_rostralACC_frontal_pole_diff")
plot(table.cor[,9],table.cor[,1], ylab="CDRS percent change", xlab="R_precuneus_postcentral_diff")

#par(mfrow=c(2,2))
plot(table.cor[,10],table.cor[,1], ylab="CDRS percent change", xlab="R_precuneus_R_fusiform_diff")
plot(table.cor[,11],table.cor[,1], ylab="CDRS percent change", xlab="R_precuneus_R_hippocampus_diff")
plot(table.cor[,12],table.cor[,1], ylab="CDRS percent change", xlab="R_precuneus_superior_frontal_diff")
plot(table.cor[,13],table.cor[,1], ylab="CDRS percent change", xlab="R_precuneus_insula_diff")

#par(mfrow=c(2,2))
plot(table.cor[,14],table.cor[,1], ylab="CDRS percent change", xlab="R_hipp_L_insula_diff")
plot(table.cor[,15],table.cor[,1], ylab="CDRS percent change", xlab="R_hipp_subcallosal_diff")
plot(table.cor[,16],table.cor[,1], ylab="CDRS percent change", xlab="R_hipp_postcing_diff")
plot(table.cor[,17],table.cor[,1], ylab="CDRS percent change", xlab="R_hipp_superior_frontal_diff")

#par(mfrow=c(2,2))
plot(table.cor[,18],table.cor[,1], ylab="CDRS percent change", xlab="R_amyg_thalamus_hippocampus_diff")
plot(table.cor[,19],table.cor[,1], ylab="CDRS percent change", xlab="L_amyg_ACC_diff")
plot(table.cor[,20],table.cor[,1], ylab="CDRS percent change", xlab="L_precuneus_L_postcing_diff")
plot(table.cor[,21],table.cor[,1], ylab="CDRS percent change", xlab="L_precuneus_L_precentral_SMA_diff")

#par(mfrow=c(2,2))
plot(table.cor[,22],table.cor[,1], ylab="CDRS percent change", xlab="L_precuneus_R_precentral_diff")

#mtext("Scatterplot of CDRS percent change vs fMRI clusters", side=3, outer=TRUE, line=-3)

###correlation and pvalue
cor.test(table.cor[,2],table.cor[,1])  
##lab="L_hipp_L_insula_diff";r=0.9524746,p-value = 0.0002589

cor.test(table.cor[,3],table.cor[,1])
##lab="L_hipp_ACC_diff", r=-0.9921732,p-value = 1.192e-06

cor.test(table.cor[,4],table.cor[,1])
##lab="L_postcing_Lfusiform_diff";r=0.975075 ,p-value = 3.799e-05
cor.test(table.cor[,5],table.cor[,1]) ##lab="L_postcing_precentral_postcentral_diff";r=-0.9913447,p-value = 1.611e-06


cor.test(table.cor[,6],table.cor[,1]) ##lab="L_postcing_R_frontal_pole_diff";r=0.9780642,p-value = 2.596e-05

cor.test(table.cor[,7],table.cor[,1]) ##lab="R_rostralACC_subcallosal_diff";r=-0.9843342 p-value = 9.499e-06
cor.test(table.cor[,8],table.cor[,1]) ##lab="R_rostralACC_frontal_pole_diff") 0.9890737,p-value = 3.234e-06
cor.test(table.cor[,9],table.cor[,1])
##lab="R_precuneus_postcentral_diff") -0.9919544 p-value = 1.294e-06


cor.test(table.cor[,10],table.cor[,1]) 
#xlab="R_precuneus_R_fusiform_diff")  0.9664632  p-value = 9.194e-05
cor.test(table.cor[,11],table.cor[,1]) #xlab="R_precuneus_R_hippocampus_diff") 0.9619185 p-value = 0.0001342
cor.test(table.cor[,12],table.cor[,1]) #xlab="R_precuneus_superior_frontal_diff")0.9840264 p-value = 1.007e-05
cor.test(table.cor[,13],table.cor[,1])
#xlab="R_precuneus_insula_diff") 0.9881985 p-value = 4.073e-06

#par(mfrow=c(2,2))
cor.test(table.cor[,14],table.cor[,1])
#xlab="R_hipp_L_insula_diff")  0.9713981 p-value = 5.725e-05
cor.test(table.cor[,15],table.cor[,1]) 
#xlab="R_hipp_subcallosal_diff")  p-value = 0.002181
cor.test(table.cor[,16],table.cor[,1])
#xlab="R_hipp_postcing_diff")-0.9878011 p-value = 4.497e-06
cor.test(table.cor[,17],table.cor[,1]) #xlab="R_hipp_superior_frontal_diff") -0.9633314 p-value = 0.0001199

#par(mfrow=c(2,2))
cor.test(table.cor[,18],table.cor[,1]) #xlab="R_amyg_thalamus_hippocampus_diff")
cor.test(table.cor[,19],table.cor[,1])
#xlab="L_amyg_ACC_diff")
cor.test(table.cor[,20],table.cor[,1])
#xlab="L_precuneus_L_postcing_diff")
cor.test(table.cor[,21],table.cor[,1]) #xlab="L_precuneus_L_precentral_SMA_diff")

#par(mfrow=c(2,2))
cor.test(table.cor[,22],table.cor[,1]) #xlab="L_precuneus_R_precentral_diff")

```

```{r,echo=FALSE}
L_hipp_L_insula<-data.frame(grid=fMRI[,1],pre=fMRI[,2],post=fMRI[,23])
L_hipp_ACC<-data.frame(grid=fMRI[,1],pre=fMRI[,3],post=fMRI[,24])
L_postcing_Lfusiform<-data.frame(grid=fMRI[,1],pre=fMRI[,4],post=fMRI[,25])
L_postcing_precentral_postcentral<-data.frame(grid=fMRI[,1],pre=fMRI[,5],post=fMRI[,26])
L_postcing_R_frontal_pole<-data.frame(grid=fMRI[,1],pre=fMRI[,6],post=fMRI[,27])
R_rostralACC_subcallosal<-data.frame(grid=fMRI[,1],pre=fMRI[,7],post=fMRI[,28])
R_rostralACC_frontal_pole<-data.frame(grid=fMRI[,1],pre=fMRI[,8],post=fMRI[,29])
R_precuneus_postcentral<-data.frame(grid=fMRI[,1],pre=fMRI[,9],post=fMRI[,30])
R_precuneus_R_fusiform<-data.frame(grid=fMRI[,1],pre=fMRI[,10],post=fMRI[,31])
R_precuneus_R_hippocampus<-data.frame(grid=fMRI[,1],pre=fMRI[,11],post=fMRI[,32])
R_precuneus_superior_frontal<-data.frame(grid=fMRI[,1],pre=fMRI[,12],post=fMRI[,33])
R_precuneus_insula<-data.frame(grid=fMRI[,1],pre=fMRI[,13],post=fMRI[,34])
R_hipp_L_insula<-data.frame(grid=fMRI[,1],pre=fMRI[,14],post=fMRI[,35])
R_hipp_subcallosal<-data.frame(grid=fMRI[,1],pre=fMRI[,15],post=fMRI[,36])
R_hipp_postcing<-data.frame(grid=fMRI[,1],pre=fMRI[,16],post=fMRI[,37])
R_hipp_superior_frontal<-data.frame(grid=fMRI[,1],pre=fMRI[,17],post=fMRI[,38])
R_amyg_thalamus_hippocampus<-data.frame(grid=fMRI[,1],pre=fMRI[,18],post=fMRI[,39])
L_amyg_ACC<-data.frame(grid=fMRI[,1],pre=fMRI[,19],post=fMRI[,40])
L_precuneus_L_postcing<-data.frame(grid=fMRI[,1],pre=fMRI[,20],post=fMRI[,41])
L_precuneus_L_precentral_SMA<-data.frame(grid=fMRI[,1],pre=fMRI[,21],post=fMRI[,42])
L_precuneus_R_precentral<-data.frame(grid=fMRI[,1],pre=fMRI[,22],post=fMRI[,43])


## long dataset##
library(reshape2)
library(ggplot2)
L_precuneus_R_precentral_long <- melt(L_precuneus_R_precentral,
                           id.vars = "grid",
                           measure.vars = c("pre","post"),
                           variable.name = "condition")
as.numeric(L_precuneus_R_precentral_long$value)
ggplot(L_precuneus_R_precentral_long, aes(x=condition, y=value, group=grid, colour=factor(grid))) +
  geom_line()+
  geom_point()+
  scale_x_discrete(limits=c("pre","post"))+
  labs(x = "Condition",
       y = "L_precuneus_R_precentral",
       title = "Baseline and  post-treatment for L_precuneus_R_precentral")+
scale_color_manual(values = c("#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#FF7F00", "#FF7F00", "#FF7F00"), guide = FALSE) + 
    theme_bw()
#################2
L_hipp_ACC_long <- melt(L_hipp_ACC,
                           id.vars = "grid",
                           measure.vars = c("pre","post"),
                           variable.name = "condition")

as.numeric(L_hipp_ACC_long$value)
ggplot(L_hipp_ACC_long, aes(x=condition, y=value, group=grid, colour=factor(grid))) +
  geom_line()+
  geom_point()+
  scale_x_discrete(limits=c("pre","post"))+
  labs(x = "Condition",
       y = "L_hipp_ACC",
       title = "Baseline and  post-treatment for L_hipp_ACC")+
scale_color_manual(values = c("#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#FF7F00", "#FF7F00", "#FF7F00"), guide = FALSE) + 
    theme_bw()
##############3
L_postcing_Lfusiform_long <- melt(L_postcing_Lfusiform,
                           id.vars = "grid",
                           measure.vars = c("pre","post"),
                           variable.name = "condition")
as.numeric(L_postcing_Lfusiform_long$value)
ggplot(L_postcing_Lfusiform_long, aes(x=condition, y=value, group=grid, colour=factor(grid))) +
  geom_line()+
  geom_point()+
  scale_x_discrete(limits=c("pre","post"))+
  labs(x = "Condition",
       y = "L_postcing_Lfusiform",
       title = "Baseline and  post-treatment for L_postcing_Lfusiform")+
scale_color_manual(values = c("#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#FF7F00", "#FF7F00", "#FF7F00"), guide = FALSE) + 
    theme_bw()
##########4
L_postcing_precentral_postcentral_long <- melt(L_postcing_precentral_postcentral,
                           id.vars = "grid",
                           measure.vars = c("pre","post"),
                           variable.name = "condition")
as.numeric(L_postcing_precentral_postcentral_long$value)
ggplot(L_postcing_precentral_postcentral_long, aes(x=condition, y=value, group=grid, colour=factor(grid))) +
  geom_line()+
  geom_point()+
  scale_x_discrete(limits=c("pre","post"))+
  labs(x = "Condition",
       y = "L_postcing_precentral_postcentral",
       title = "Baseline and  post-treatment for L_postcing_precentral_postcentral")+
scale_color_manual(values = c("#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#FF7F00", "#FF7F00", "#FF7F00"), guide = FALSE) + 
    theme_bw()

#####5
L_postcing_R_frontal_pole_long <- melt(L_postcing_R_frontal_pole,
                           id.vars = "grid",
                           measure.vars = c("pre","post"),
                           variable.name = "condition")
as.numeric(L_postcing_R_frontal_pole_long$value)
ggplot(L_postcing_R_frontal_pole_long, aes(x=condition, y=value, group=grid, colour=factor(grid))) +
  geom_line()+
  geom_point()+
  scale_x_discrete(limits=c("pre","post"))+
  labs(x = "Condition",
       y = "L_postcing_R_frontal_pole",
       title = "Baseline and  post-treatment for L_postcing_R_frontal_pole")+
scale_color_manual(values = c("#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#FF7F00", "#FF7F00", "#FF7F00"), guide = FALSE) + 
    theme_bw()
#####6
R_rostralACC_subcallosal_long <- melt(R_rostralACC_subcallosal,
                           id.vars = "grid",
                           measure.vars = c("pre","post"),
                           variable.name = "condition")
as.numeric(R_rostralACC_subcallosal_long$value)
ggplot(R_rostralACC_subcallosal_long, aes(x=condition, y=value, group=grid, colour=factor(grid))) +
  geom_line()+
  geom_point()+
  scale_x_discrete(limits=c("pre","post"))+
  labs(x = "Condition",
       y = "R_rostralACC_subcallosal",
       title = "Baseline and  post-treatment for R_rostralACC_subcallosal")+
scale_color_manual(values = c("#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#FF7F00", "#FF7F00", "#FF7F00"), guide = FALSE) + 
    theme_bw()
```
