---
title: "fMRI"
author: "Yanan Ren"
date: "2016Äê11ÔÂ9ÈÕ"
output: word_document
---

```{r, echo=FALSE}
fMRI2<-read.csv("D:/Biostatistics/2016FallRA/dataset/ketamine_clusters_2.csv", header=T, sep=',')
attach(fMRI2)
View(fMRI2)

##mean and sd##
bl_mean_fMRI2<-as.data.frame(apply(fMRI2[,3:8], 2, mean))
bl_mean_fMRI2
baseline_mean<-round(bl_mean_fMRI2[,1],3)
baseline_mean

ptx_mean_fMRI2<-as.data.frame(apply(fMRI2[,11:16], 2, mean))
ptx_mean_fMRI2
ptx_trt_mean<-round(ptx_mean_fMRI2[,1],3)
ptx_trt_mean

bl_sd_fMRI2<-as.data.frame(apply(fMRI2[,3:8], 2, sd))
bl_sd_fMRI2
baseline_sd<-round(bl_sd_fMRI2[,1],3)
baseline_sd

ptx_sd_fMRI2<-as.data.frame(apply(fMRI2[,11:16], 2, sd))
ptx_sd_fMRI2
ptx_trt_sd<-round(ptx_sd_fMRI2[,1],3)
ptx_trt_sd


Baseline<-paste(baseline_mean,"¡À",baseline_sd, sep=" ")
Baseline
Post_treatment<-paste(ptx_trt_mean,"¡À",ptx_trt_sd, sep=" ")
Post_treatment

names<-colnames(fMRI2)
newname<-substr(names[3:8],10,nchar(names[3:8]))

#fMRI2_table<-data.frame(newname,Baseline,Post_treatment)

#library(knitr)
#kable(fMRI_table, caption = "Table 1. Baseline and Post-treatment of fMRI")
```

##2
```{r, echo=FALSE}
cdrs_prechange<-c(0.41,-0.14,0.29,0.30,0.24,0.675,0.78,0.59)
R_postcing_R_postcentral_diff<-fMRI2[,11]-fMRI2[,3]
R_postcing_R_precentral_diff<-fMRI2[,12]-fMRI2[,4]
R_postcing_R_superiorfrontal_diff<-fMRI2[,13]-fMRI2[,5]
R_postcing_R_rostralACC_diff<-fMRI2[,14]-fMRI2[,6]
R_postcing_L_rostralACC_diff<-fMRI2[,15]-fMRI2[,7]
R_postcing_subcallosal_diff<-fMRI2[,16]-fMRI2[,8]

table.cor<-data.frame(cdrs_prechange, R_postcing_R_postcentral_diff, R_postcing_R_precentral_diff, R_postcing_R_superiorfrontal_diff, R_postcing_R_rostralACC_diff, R_postcing_L_rostralACC_diff, R_postcing_subcallosal_diff)
View(table.cor)
##one sample t-test##
## one sample t-test for diff with Ho: mu=0 Ha=not equal to 0 
##0.3318621 p-value = 0.1671
t.test(table.cor[,2], mu=0, alternative="two.sided", conf.level=0.95)

##-0.2707354 p-value = 0.6929
t.test(table.cor[,3], mu=0, alternative="two.sided", conf.level=0.95)

##0.1294889 p-value = 0.386
t.test(table.cor[,4], mu=0, alternative="two.sided", conf.level=0.95)

## -0.639403 p-value = 0.8651
t.test(table.cor[,5], mu=0, alternative="two.sided", conf.level=0.95)

## -0.08661625 p-value = 0.5639
t.test(table.cor[,6], mu=0, alternative="two.sided", conf.level=0.95)

##-0.4005255   p-value = 0.787
t.test(table.cor[,7], mu=0, alternative="two.sided", conf.level=0.95)



diff<-round(c(0.1179576,-0.1017964,-0.4549369,-0.4654981,-0.2665409,-0.2793397),3)
p.value<-round(c(0.8734,0.8935,0.4979,0.5179,0.6169,0.5526),3)
fMRI_table.2<-data.frame(newname,Baseline,Post_treatment,diff,p.value)

library(knitr)
kable(fMRI_table.2, caption = "Table 2. Baseline and Post-treatment of fMRI")
```


```{r,echo=FALSE}
##plot##

plot(table.cor[,2],table.cor[,1], ylab="CDRS percent change", xlab="R_postcing_R_postcentral_diff")
plot(table.cor[,3],table.cor[,1], ylab="CDRS percent change", xlab="R_postcing_R_precentral_diff")
plot(table.cor[,4],table.cor[,1], ylab="CDRS percent change", xlab="R_postcing_R_superiorfrontal_diff")
plot(table.cor[,5],table.cor[,1], ylab="CDRS percent change", xlab="R_postcing_R_rostralACC_diff")
plot(table.cor[,6],table.cor[,1], ylab="CDRS percent change", xlab="R_postcing_L_rostralACC_diff")
plot(table.cor[,7],table.cor[,1], ylab="CDRS percent change", xlab="R_postcing_subcallosal_diff")

###correlation and pvalue
cor.test(table.cor[,2],table.cor[,1])  
##lab="L_hipp_L_insula_diff";r=-0.969,p-value = 7.18e-05

cor.test(table.cor[,3],table.cor[,1])
##lab="L_hipp_ACC_diff", r=-0.951,p-value = 0.000283

cor.test(table.cor[,4],table.cor[,1])
##lab="L_postcing_Lfusiform_diff";r=0.963  ,p-value = 0.000126
cor.test(table.cor[,5],table.cor[,1]) ##lab="L_postcing_precentral_postcentral_diff";r=0.961,p-value = 0.0001412

cor.test(table.cor[,6],table.cor[,1]) ##lab="L_postcing_R_frontal_pole_diff";r=-0.956,p-value = 0.0002071

cor.test(table.cor[,7],table.cor[,1]) ##lab="R_rostralACC_subcallosal_diff";r=-0.981 p-value = 1.81e-05

```


```{r,echo=FALSE}
R_postcing_R_postcentral<-data.frame(grid=fMRI2[,1],pre=fMRI2[,3],post=fMRI2[,11])
R_postcing_R_precentral<-data.frame(grid=fMRI2[,1],pre=fMRI2[,4],post=fMRI2[,12])
R_postcing_R_superiorfrontal<-data.frame(grid=fMRI2[,1],pre=fMRI2[,5],post=fMRI2[,13])
R_postcing_R_rostralACC<-data.frame(grid=fMRI2[,1],pre=fMRI2[,6],post=fMRI2[,14])
R_postcing_L_rostralACC<-data.frame(grid=fMRI2[,1],pre=fMRI2[,7],post=fMRI2[,15])
R_postcing_subcallosal<-data.frame(grid=fMRI2[,1],pre=fMRI2[,8],post=fMRI2[,16])


## long dataset## 
library(reshape2)
library(ggplot2)
R_postcing_subcallosal_long <- melt(R_postcing_subcallosal,
                           id.vars = "grid",
                           measure.vars = c("pre","post"),
                           variable.name = "condition")
as.numeric(R_postcing_subcallosal_long$value)
ggplot(R_postcing_subcallosal_long, aes(x=condition, y=value, group=grid, colour=factor(grid))) +
  geom_line()+
  geom_point()+
  scale_x_discrete(limits=c("pre","post"))+
  labs(x = "Condition",
       y = "R_postcing_subcallosal",
       title = "Baseline and  post-treatment for R_postcing_subcallosal")+
scale_color_manual(values = c("#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#1C86EE", "#FF7F00", "#FF7F00", "#FF7F00"), guide = FALSE) + 
    theme_bw()


```